# Generated by Django 5.1.3 on 2024-11-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_diploma_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='users.team'),
        ),
    ]
