# Generated by Django 5.1.3 on 2024-11-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_diploma_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diploma_teacher', to='users.team'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_team', to='users.team'),
        ),
    ]
