# Generated by Django 5.1.3 on 2024-11-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teachers_list', to='users.team'),
        ),
    ]
