# Generated by Django 5.1.3 on 2024-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_teacher_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='teams', to='users.skill'),
        ),
    ]
